#!/bin/bash
# LaTeX Packages from tinytex:::install_yihui_pkgs()
# Ref: https://github.com/yihui/tinytex/blob/master/tools/pkgs-yihui.txt
tlmgr install a4wide
tlmgr install achemso
tlmgr install adjustbox
tlmgr install ae
tlmgr install algorithmicx
tlmgr install algorithms
tlmgr install ametsoc
tlmgr install amscls
tlmgr install apacite
tlmgr install appendix
tlmgr install awesomebox
tlmgr install babel-english
tlmgr install babel-french
tlmgr install bbm-macros
tlmgr install beamer
tlmgr install biber
tlmgr install biblatex
tlmgr install bookmark
tlmgr install breakurl
tlmgr install caption
tlmgr install carlisle
tlmgr install catoptions
tlmgr install ccicons
tlmgr install charter
tlmgr install chemgreek
tlmgr install cite
tlmgr install cleveref
tlmgr install collectbox
tlmgr install colortbl
tlmgr install comment
tlmgr install courier
tlmgr install crop
tlmgr install csquotes
tlmgr install datetime
tlmgr install dblfloatfix
tlmgr install doclicense
tlmgr install draftwatermark
tlmgr install eepic
tlmgr install endfloat
tlmgr install endnotes
tlmgr install enumitem
tlmgr install environ
tlmgr install epsf
tlmgr install epstopdf
tlmgr install eso-pic
tlmgr install esvect
tlmgr install etex-pkg
tlmgr install eurosym
tlmgr install everysel
tlmgr install expex
tlmgr install extsizes
tlmgr install fancyhdr
tlmgr install floatflt
tlmgr install floatrow
tlmgr install fmtcount
tlmgr install fontawesome5
tlmgr install fontaxes
tlmgr install footmisc
tlmgr install forarray
tlmgr install hardwrap
tlmgr install hyperxmp
tlmgr install hyphen-french
tlmgr install hyphenat
tlmgr install jknapltx
tlmgr install koma-script
tlmgr install langsci
tlmgr install lastpage
tlmgr install lettrine
tlmgr install libertine
tlmgr install lineno
tlmgr install lipsum
tlmgr install listings
tlmgr install logreq
tlmgr install ltxkeys
tlmgr install ly1
tlmgr install makecell
tlmgr install marginnote
tlmgr install marvosym
tlmgr install mathalpha
tlmgr install mathpazo
tlmgr install mathspec
tlmgr install mathtools
tlmgr install mdframed
tlmgr install memoir
tlmgr install metalogo
tlmgr install mhchem
tlmgr install microtype
tlmgr install minifp
tlmgr install mnras
tlmgr install modes
tlmgr install morefloats
tlmgr install moreverb
tlmgr install ms
tlmgr install multirow
tlmgr install mweights
tlmgr install ncntrsbk
tlmgr install needspace
tlmgr install newfloat
tlmgr install newtx
tlmgr install ntgclass
tlmgr install palatino
tlmgr install parskip
tlmgr install pbox
tlmgr install pdflscape
tlmgr install pdfpages
tlmgr install pdfsync
tlmgr install pgf
tlmgr install picinpar
tlmgr install polyglossia
tlmgr install preprint
tlmgr install preview
tlmgr install psfrag
tlmgr install ragged2e
tlmgr install realscripts
tlmgr install revtex4-1
tlmgr install roboto
tlmgr install rsfs
tlmgr install sectsty
tlmgr install seqsplit
tlmgr install setspace
tlmgr install sidecap
tlmgr install siunitx
tlmgr install soul
tlmgr install soulutf8
tlmgr install srcltx
tlmgr install standalone
tlmgr install stix
tlmgr install stmaryrd
tlmgr install sttools
tlmgr install subfig
tlmgr install subfigure
tlmgr install symbol
tlmgr install tabto-ltx
tlmgr install tabu
tlmgr install tcolorbox
tlmgr install tex-gyre
tlmgr install textcase
tlmgr install thmtools
tlmgr install threeparttable
tlmgr install threeparttablex
tlmgr install thumbpdf
tlmgr install titlesec
tlmgr install totcount
tlmgr install totpages
tlmgr install translator
tlmgr install trimspaces
tlmgr install tufte-latex
tlmgr install ucs
tlmgr install ulem
tlmgr install units
tlmgr install upquote
tlmgr install urlbst
tlmgr install varwidth
tlmgr install vmargin
tlmgr install vruler
tlmgr install wallpaper
tlmgr install wrapfig
tlmgr install xargs
tlmgr install xltxtra
tlmgr install xstring
tlmgr install xwatermark
tlmgr install xypic
tlmgr install zapfchan
tlmgr install zref